### ISSUE TITLE
Cleanup not working on GCS bucket in interop mode

### ISSUE THREAD

**Issue by leighmhart** [minio/warp#200]
Hi team,

While testing this fantastic tool against a GCS storage bucket using s3 interop the tests work but clean up fails with nondescript errors:

```bash
$ env|grep -i warp
WARP_SECRET_KEY=xxxx
WARP_ACCESS_KEY=yyyy
WARP_HOST=storage.googleapis.com

$ warp --debug get --bucket mygooglecloudstoragebucketnamehere --duration=5s
warp: <ERROR> Invalid argument.
warp: <ERROR> EOF
Preparing:              ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  38.60%
Benchmarking:            00m01s / 00m05s ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  35.00%
warp: Benchmark data written to "warp-get-2021-12-01[212316]-4Jei.csv.zst"

----------------------------------------
Operation: PUT
* Average: 1131.20 MiB/s, 113.12 obj/s

Throughput, split into 21 x 1s:
 * Fastest: 1156.6MiB/s, 115.66 obj/s
 * 50% Median: 1135.5MiB/s, 113.55 obj/s
 * Slowest: 1077.2MiB/s, 107.72 obj/s

----------------------------------------
Operation: GET
* Average: 1339.08 MiB/s, 133.91 obj/s

Throughput, split into 4 x 1s:
 * Fastest: 1487.5MiB/s, 148.75 obj/s
 * 50% Median: 1336.3MiB/s, 133.63 obj/s
 * Slowest: 1262.2MiB/s, 126.22 obj/s
warp: <ERROR> Invalid argument.
warp: <ERROR> EOF
Clearing Prefix "mygooglecloudstoragebucketnamehere/vJ3uavd6/"...warp: <ERROR> Invalid argument.
warp: <ERROR> EOF
warp: <ERROR> Invalid argument.
warp: <ERROR> EOF
```

the bucket is left with the usual large collection of 20 folders, rnd files still present.

**Comment by harshavardhana** [comment]
> ```shell
> warp: <ERROR> Invalid argument.
> warp: <ERROR> EOF
> Clearing Prefix "mygooglecloudstoragebucketnamehere/vJ3uavd6/"...warp: <ERROR> Invalid argument.
> warp: <ERROR> EOF
> warp: <ERROR> Invalid argument.
> warp: <ERROR> EOF
> ```

GCS is broken with their interop implementation @leighmhart - here is the list of things that are broken in GCS - S3 interop mode.  This is out of scope for `warp`

Warp requires S3 targets to support full S3 API.

| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [ListObjectVersions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |

GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~ mc ls --versions gcs/harshavardhana
mc: <ERROR> Unable to list folder. unrecognized option:Marker
```

| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [GetBucketEncryption](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketEncryption.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |


GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~  mc encrypt info gcs/harshavardhana
mc: <ERROR> Unable to get encryption info: 503 Service Unavailable.
```

| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [PutBucketLifecycle](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |

GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~ mc ilm add gcs/harshavardhana --expiry-days 365
mc: <ERROR> Unable to set new lifecycle rules. The XML you provided was not well-formed or did not validate against our published schema.
```

| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [SelectObjectContent](https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |

GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~ mc sql gcs/harshavardhana/hosts.csv
mc: <ERROR> Unable to run sql Invalid argument.
```

| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [MultiObjectDelete](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |

GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~ mc rm gcs/harshavardhana/hosts
Removing `gcs/harshavardhana/hosts`.
mc: <ERROR> Failed to remove `gcs/harshavardhana/hosts`. Invalid argument.
```


| API | AWS S3 | MinIO | GCS (S3 compatibility)|
| :-------------| ------------------- | -------------------  | ------------------- |
| [PutObjectTags](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) | :heavy_check_mark: | :heavy_check_mark: | :heavy_exclamation_mark: |

GCS fails in this manner while they succeed on AWS S3 and MinIO fine.
```
~ mc tag set gcs/harshavardhana/hosts "key1=value1&key2=value2&key3=value3"
mc: <ERROR> Failed to set tags for https://storage.googleapis.com/harshavardhana/hosts: 503 Service Unavailable.
```

### Summary
AWS S3 API Compatibility is quite limited, since few basic APIs do not work well. Other APIs that are not mentioned are not part of GCS S3 compatibility layer implementation are

**Comment by leighmhart** [comment]
thanks @harshavardhana - appreciated!
