### ISSUE TITLE
Mixed workload paramters clarification

### ISSUE THREAD

**Issue by Badb0yBadb0y** [minio/warp#201]
Hello,

It's not really detailed what the following parameters means in the mixed workload so it's difficult to generate my workload:

_The distribution of operations can be adjusted with the --get-distrib, --stat-distrib, --put-distrib and --delete-distrib parameters._

I'd like to mimic this with the tests:
PUT: 9379 47% PUT
GET: 7111 36% get
DELETE: 3410 17% delete
19900 altogether

Tried with 2 different way
- Defined as a percentage that I want to achieve: 
warp mixed --noclear --put-distrib=47 --get-distrib=36 --delete-distrib=17 --duration=5h --objects=1000000 --obj.size=40k --bucket=2andhalfbillion --host=...
- Defined as a calculation based on the default 20 concurrency, so if the below values multiplied with 20, I should get that number that I want
warp mixed --noclear --put-distrib=469 --get-distrib=356 --delete-distrib=171 --duration=5h --objects=1000000 --obj.size=40k --bucket=2andhalfbillion --host=...

but still not proper numbers. 

If you can see my graph, it's a way more higher (take into consideration only the delete and the get because there is a ut operation running next to those)
[Graph](https://i.ibb.co/p1CXqBn/Capture.png)

How is the proper way to mimic my workload?

**Comment by klauspost** [comment]
You must set the `--stat-distrib=0`, otherwise it will use the default value on 30.

```
warp mixed --put-distrib=47 --get-distrib=36 --delete-distrib=17 --stat-distrib=0 ...
```

Without setting, the distribution will be ~

op: GET dist: 27.7%
op: STAT dist: 23.1%
op: PUT dist: 36.2%
op: DELETE dist: 13.1%

This does not include the initial 1M PUT requests.

Your graph doesn't really make sense to me. If I read it correctly you have something else running while the benchmark is running. Hard to tell.

Maybe try shorter runs until you get the settings as you want, then do a longer with more initial objects.

**Comment by Badb0yBadb0y** [comment]
Ok, let me try, thank you.
