### ISSUE TITLE
No use of --objects flag

### ISSUE THREAD

**Issue by shreyanshjain7174** [minio/warp#263]
In mixed category, I am trying to use only put distribution at 100% and all other are being set as 0 that means it wshould take only write operations at 100% of the objects provided. Whereas when we supply --objects flag it doesn't write exactly that many objects, if the benchmark is running for a longer duration it takes the precedence and for that duration it writes the objects as many as it can. Then there;s no point in having two such flags one should be optional always both flags can't be supplied at the same time and you have made duration as global flag so it will always follow that duration for the benchmark.

```
date ;warp mixed --put-distrib 100 --obj.size 256KiB  --concurrent=1 --warp-client=172.17.50.124:8001 --host=172.17.50.124:5000  --access-key=$newaccess --secret-key=$newsecret --bucket testput --benchdata testput --objects 500 --duration=2m --host-select=roundrobin  --no-color --debug --noclear ;date
Thu Jun  1 10:01:11 UTC 2023
warp: Benchmark data written to "testput.csv.zst"
warp: Cleanup done.
Thu Jun  1 10:03:22 UTC 2023


:~/warp
# objs |grep -A2 testput
Thu Jun  1 10:06:14 UTC 2023
        "bucket": "testput",
        "num_shards": 11,
                "num_objects": 9864
                
```

**Comment by klauspost** [comment]
I don't understand what your point is.

Use `warp put` benchmark if you want to test 100% PUT operations.

**Comment by shreyanshjain7174** [comment]
@klauspost I wanted to write specific number of objects but `warp put` doesn't have that flag it only has duration. Also mixed should support the idea of number of objects to write per bucket but the `--objects` flag doesn't behave the way it is intended to.

**Comment by klauspost** [comment]
@shreyanshjain7174 `--objects` is the number of seed objects before the actual benchmark is run. The benchmark includes PUT operations which will add more.

If you want a specific number, set it on `warp get --duration=5s`. The GET benchmark will be useless, but it will record the PUT phase as a separate benchmark.

**Comment by shreyanshjain7174** [comment]
@klauspost thanks! that answers my question I wanted to write the objects till a specific amount so I supplied `--duration 0s` and I am satisfied with the result it gave.

**Comment by akshay8043** [comment]
@shreyanshjain7174 . So did that work for you?

fill the bucket with lets say 300 million objects of 150KB object size using warp mixed and put-distrib 100?

I was not using --duration 0s before, and I am using warp 1.0.3. I had 2x different client and when I was using single client, it finished but when i used 2 different clients and it was killing the warp client possibly because of out of memory. It was using all 512GB of ram on my bare metal client. 


warp mixed --put-distrib=100 --stat-distrib=0 --get-distrib=0 --delete-distrib=0 --access-key=xxxx --secret-key=xxxxxx --objects=30000000 --obj.size=150K --warp-client=xx.xx.xx.{xx...xx}:7761 --bucket=warp-bucket2 --host=xx.xx.xx.{xxx...xxx}:xx --noclear --benchdata=128KB-write --concurrent=100 --duration 0s | tee 128KB-write


I only want to fill the bucket as quickly as possibly with 150KB object size and 300 million objects.

**Comment by shreyanshjain7174** [comment]
@akshay8043 I had requested for the same in the put workload but the workaround didn't worked for me, instead I worked out my own version and a workaround [here](https://github.com/shreyanshjain7174/warp/releases/tag/v0.8.0) if you install this binary you will see put workload with --objects and it will stop the benchmark when it fills the desired number of objects. Can't be used with duration, as duration will always take precedence, so to mitigate that the default value of duration has been set to 48hrs in which case we don't run the put till the space runs out.

**Comment by akshay8043** [comment]
@shreyanshjain7174 The problem with latest binary is they have either removed --objects from put or it didnt exist before.

I am sorry if i misunderstood your note in last line. I had to use alternate method to fill the bucket, i used warp mixed with no clear option, keeping all other distribution to 0 except the put-distrib. I was still facing someissues here as well can't remember, but i had cancelled and reran mixed tests multiple times to fill 800M objects of 150KB
